### ISSUE TITLE
Mot de passe en clair et adresse hors variable.

### ISSUE THREAD

**Issue by CharlesRigal** [CharlesRigal/projet-moto-back#2]
stp passe par une variable d’environnement pour mdp address

**Comment by RichardDuclos** [comment]
de quoi tu parles

**Comment by CharlesRigal** [comment]
ton dernier commit

**Comment by RichardDuclos** [comment]
ah oui dans alembic.ini j'ai pas reussi a le mettre en variable d'environnement

**Comment by CharlesRigal** [comment]
sqlalchemy.url = postgresql://richard-admin:WeH|=$/HP/Fk(1w.cb^n@82.65.153.125:5432/moto-dev

**Comment by CharlesRigal** [comment]
ha ok je regarde quand je rentre
